BEGIN;

ALTER TABLE v2_tasks
	ADD COLUMN IF NOT EXISTS author TEXT,
	ADD COLUMN IF NOT EXISTS series_name TEXT,
	ADD COLUMN IF NOT EXISTS comic_name TEXT,
	ADD COLUMN IF NOT EXISTS summary TEXT,
	ADD COLUMN IF NOT EXISTS tags_raw TEXT,
	ADD COLUMN IF NOT EXISTS tags_normalized TEXT,
	ADD COLUMN IF NOT EXISTS genres_raw TEXT,
	ADD COLUMN IF NOT EXISTS genres_normalized TEXT;

COMMIT;
